# Generated by Django 5.0 on 2024-01-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expensereset_user_alter_incomereset_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
